name: flutter_architecture_template
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  
  # state management
  flutter_bloc: ^8.0.1

  # dependency injection
  get_it: ^7.2.0
  injectable: ^1.5.3

  # network
  dio: ^4.0.4
  connectivity_plus: ^2.2.0

  # utility
  dartz: ^0.10.1
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0

  # firebase packages
  firebase_core: ^1.4.0
  firebase_messaging: ^10.0.4

  # notification
  flutter_local_notifications: ^8.1.1+2

dev_dependencies:
  build_runner: null
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.3
  mockito: ^5.0.17
  freezed: ^1.1.1
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true
